### ISSUE TITLE
Toptica iBeam support

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/microscope#102]
@iandobbie has initial support for Toptica iBeam smart. Their interface is completely different from the iChrome multi-laser engine.

**Comment by carandraug** [comment]
I was reviewing this from Ian's `toptica-laser` branch. This was copied from the cobolt laser and some of its methods still send commands meant for the cobolt. I couldn't find the manual on micronadmin so will ask toptica.

**Comment by iandobbie** [comment]
I have a physical manual. Sorry if I didn't deal with all the functions. I will dig out the manual and check all the commands used.

**Comment by carandraug** [comment]
Toptica sent us the manual in pdf.

**Comment by carandraug** [comment]
Added with cf33b74 so closing as fixed.
