### ISSUE TITLE
Fork issue on macos 10.14

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/microscope#106]
On my mac laptop starting the ximea camera gives and error :

objc[16270]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.

Solution from...

https://stackoverflow.com/questions/50168647/multiprocessing-causes-python-to-crash-and-gives-an-error-may-have-been-in-progr

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

before starting microscope

Mick suggests we put this into the system environment if we are running on a mac.

**Comment by carandraug** [comment]
Merged and pushed. Closing as fixed.
