### ISSUE TITLE
fail to get sensor shape in ximea camera

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/microscope#107]
The ximea driver has a bug in the sensor shape code. Don't know how this ever worked!

    def _get_sensor_shape(self):
        return (self.img.width,self.image.height)

I also could quite work out how this is meant to get initialised as beamdelta doesn't do the right magic (or not the same magic as cockpit anyway)

**Comment by carandraug** [comment]
I just tested this with Ian on his Mac and we can no longer reproduce the issue. Closing.
