### ISSUE TITLE
deviceserver problems under Windows

### ISSUE THREAD

**Issue by mickp** [MicronOxford/microscope#30]
The deviceserver process management works well on my Windows workstation, but fails to shutdown child processes on my Windows laptop. 

Also, the use of the signals module means that the deviceserver can't be wrapped behind a windows service, which seems to be the only way to have scripts start automatically without logging in. Doing so raises the error "signals only works in the main thread", although querying the thread name at that point, it says it *is* the main thread. 

We probably need to use separate event types under UNIX (signal) and Windows (win32event).

**Comment by iandobbie** [comment]
This must be solved as we are using microscope routinely on windows and linux.

**Comment by carandraug** [comment]
For future reference, looking into the logs, I'm guessing this was fixed in 28bda20a8040 .
