### ISSUE TITLE
add support for Coherent OBIS

### ISSUE THREAD

**Issue by carandraug** [MicronOxford/microscope#52]
I took a look at the OBIS Operator's manual and the control for the Coherent OBIS is completely different of the control for the Coherent Sapphire :/

**Comment by juliomateoslangerak** [comment]
I have a working implementation.
I will do a pull request

**Comment by juliomateoslangerak** [comment]
Hi,
I pulled support for the OBIS laser #55

**Comment by juliomateoslangerak** [comment]
OBIS laser is working for me. Have to implement a more clear report of the state of the laser as it is encoded.
