### ISSUE TITLE
pip install fails on fresh  Mac os install.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/microscope#57]
I took an old mac with a blank python tree (macos 10.12.5)
Installed homebrew
Installed python3 (brew install python3)
pip3 install microscope 
Fails with 
ModuleNotFoundError: No module named 'sphinx'

pip3 install sphinx, followed by pip3 install microscope works.

**Comment by carandraug** [comment]
Duplicate of issue #47 which is already fixed and will be part of the next release. Closing as fixed.
